[workspace]
resolver = "2"
members = [
  "src-tauri", "entity"
]

[workspace.package]
authors = ["HubertK05 <hubert.klimowicz.hk@gmail.com>"]
license = "MIT"
repository = "https://github.com/HubertK05/banban"