[package]
name = "entity"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "1.1.4" }
serde = { version = "1.0", features = ["derive"] }