//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::activities::Entity as Activities;
pub use super::categories::Entity as Categories;
pub use super::columns::Entity as Columns;
pub use super::tags::Entity as Tags;
